# Import Pandas Library

In [11]:
import pandas as pd

# Read the Extracted Features Datasets

In [12]:
## Extracted Features for Cleaved octapeptide
amino_acid_binary_profile_cleaved = pd.read_csv("extracted_features_dataset/Amino acid Binary Profile (AABP)(cleaved).csv")
bond_composition_cleaved =pd.read_csv("extracted_features_dataset/Bond Composition (cleaved).csv")
physicochemical_properties_cleaved = pd.read_csv("extracted_features_dataset/Physico-Chemical Properties (cleaved).csv")

## Extracted Features for Uncleaved octapeptide
amino_acid_binary_profile_uncleaved = pd.read_csv("extracted_features_dataset/Amino acid Binary Profile (AABP)(uncleaved).csv")
bond_composition_uncleaved =pd.read_csv("extracted_features_dataset/Bond Composition (uncleaved).csv")
physicochemical_properties_uncleaved = pd.read_csv("extracted_features_dataset/Physico-Chemical Properties (uncleaved).csv")

# Combine the Extracted Features Datasets into one DF

In [13]:
## Combining the datasets of cleaved octapeptides into one and relabelling it

cleaved_dataset = pd.concat([amino_acid_binary_profile_cleaved, bond_composition_cleaved, 
                             physicochemical_properties_cleaved.drop("PCP_SM", axis=1)], axis=1)
cleaved_dataset

,ID,A1,C1,D1,E1,F1,G1,H1,I1,K1,...,PCP_NP,PCP_AL,PCP_CY,PCP_AR,PCP_AC,PCP_BS,PCP_NE_pH,PCP_HB,PCP_HL,PCP_SC
0,Seq_1,1,0,0,0,0,0,0,0,0,...,0.500,0.250,0.000,0.250,0.250,0.125,0.625,0.625,0.125,0.125
1,Seq_2,0,0,0,0,0,0,1,0,0,...,0.625,0.625,0.000,0.125,0.125,0.125,0.750,0.625,0.125,0.000
2,Seq_3,0,0,0,0,0,0,0,0,0,...,0.500,0.125,0.000,0.250,0.125,0.000,0.875,0.750,0.000,0.125
3,Seq_4,1,0,0,0,0,0,0,0,0,...,0.625,0.500,0.000,0.125,0.375,0.000,0.625,0.625,0.000,0.000
4,Seq_5,0,0,0,0,0,0,0,0,0,...,0.625,0.375,0.250,0.250,0.375,0.000,0.625,0.625,0.250,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,Seq_997,0,0,0,0,0,0,0,0,0,...,0.625,0.500,0.125,0.125,0.250,0.000,0.750,0.625,0.125,0.125
997,Seq_998,0,0,0,0,0,0,0,0,0,...,0.375,0.250,0.000,0.125,0.250,0.125,0.625,0.250,0.125,0.125
998,Seq_999,0,0,0,0,0,0,0,0,0,...,0.375,0.375,0.000,0.250,0.125,0.000,0.875,0.375,0.125,0.000
999,Seq_1000,0,0,0,0,0,0,0,0,0,...,0.625,0.500,0.000,0.250,0.125,0.000,0.875,0.625,0.000,0.000
1000,Seq_1001,0,0,0,0,0,0,0,0,0,...,0.500,0.500,0.000,0.125,0.250,0.000,0.750,0.500,0.000,0.000

In [14]:
## Generating the labels for cleaved dataset

cleaved_label = pd.Series(["cleaved" for i in range(1001)], name="cleavage Status")

In [15]:
cleaved_dataset_labelled = pd.concat([cleaved_dataset, cleaved_label], axis=1)
cleaved_dataset_labelled

,ID,A1,C1,D1,E1,F1,G1,H1,I1,K1,...,PCP_AL,PCP_CY,PCP_AR,PCP_AC,PCP_BS,PCP_NE_pH,PCP_HB,PCP_HL,PCP_SC,cleavage Status
0,Seq_1,1,0,0,0,0,0,0,0,0,...,0.250,0.000,0.250,0.250,0.125,0.625,0.625,0.125,0.125,cleaved
1,Seq_2,0,0,0,0,0,0,1,0,0,...,0.625,0.000,0.125,0.125,0.125,0.750,0.625,0.125,0.000,cleaved
2,Seq_3,0,0,0,0,0,0,0,0,0,...,0.125,0.000,0.250,0.125,0.000,0.875,0.750,0.000,0.125,cleaved
3,Seq_4,1,0,0,0,0,0,0,0,0,...,0.500,0.000,0.125,0.375,0.000,0.625,0.625,0.000,0.000,cleaved
4,Seq_5,0,0,0,0,0,0,0,0,0,...,0.375,0.250,0.250,0.375,0.000,0.625,0.625,0.250,0.000,cleaved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,Seq_997,0,0,0,0,0,0,0,0,0,...,0.500,0.125,0.125,0.250,0.000,0.750,0.625,0.125,0.125,cleaved
997,Seq_998,0,0,0,0,0,0,0,0,0,...,0.250,0.000,0.125,0.250,0.125,0.625,0.250,0.125,0.125,cleaved
998,Seq_999,0,0,0,0,0,0,0,0,0,...,0.375,0.000,0.250,0.125,0.000,0.875,0.375,0.125,0.000,cleaved
999,Seq_1000,0,0,0,0,0,0,0,0,0,...,0.500,0.000,0.250,0.125,0.000,0.875,0.625,0.000,0.000,cleaved
1000,Seq_1001,0,0,0,0,0,0,0,0,0,...,0.500,0.000,0.125,0.250,0.000,0.750,0.500,0.000,0.000,cleaved

In [16]:
## Combining the datasets of non-cleaved octapeptides into one and relabelling it

uncleaved_dataset = pd.concat([amino_acid_binary_profile_uncleaved, bond_composition_uncleaved, 
                               physicochemical_properties_uncleaved], axis=1)
uncleaved_dataset

,ID,A1,C1,D1,E1,F1,G1,H1,I1,K1,...,PCP_NP,PCP_AL,PCP_CY,PCP_AR,PCP_AC,PCP_BS,PCP_NE_pH,PCP_HB,PCP_HL,PCP_SC
0,Seq_1,1,0,0,0,0,0,0,0,0,...,0.375,0.250,0.000,0.125,0.125,0.375,0.500,0.375,0.375,0.000
1,Seq_2,0,0,0,0,0,0,0,0,0,...,0.375,0.250,0.000,0.000,0.125,0.000,0.875,0.500,0.000,0.125
2,Seq_3,0,0,0,0,0,0,0,0,0,...,0.125,0.000,0.000,0.125,0.000,0.000,1.000,0.250,0.250,0.250
3,Seq_4,0,0,0,0,0,0,0,0,0,...,0.375,0.375,0.125,0.000,0.000,0.125,0.875,0.500,0.375,0.125
4,Seq_5,0,0,0,0,0,1,0,0,0,...,0.250,0.250,0.125,0.125,0.000,0.125,0.875,0.250,0.375,0.125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4842,Seq_4843,0,0,0,0,0,0,0,0,0,...,0.500,0.375,0.125,0.250,0.000,0.125,0.875,0.750,0.250,0.000
4843,Seq_4844,0,0,0,0,0,0,0,0,0,...,0.500,0.500,0.000,0.125,0.000,0.125,0.875,0.250,0.125,0.000
4844,Seq_4845,0,0,0,0,0,0,0,0,0,...,0.375,0.375,0.000,0.125,0.125,0.000,0.875,0.375,0.125,0.000
4845,Seq_4846,0,0,0,0,0,0,0,0,0,...,0.500,0.375,0.125,0.250,0.250,0.000,0.750,0.375,0.125,0.000
4846,Seq_4847,0,0,0,0,0,0,0,0,0,...,0.250,0.250,0.000,0.250,0.125,0.000,0.875,0.250,0.000,0.000

In [17]:
## Generating the labels for non-cleaved dataset

uncleaved_label = pd.Series(["uncleaved" for i in range(4847)], name="cleavage Status")

In [18]:
uncleaved_dataset_labelled = pd.concat([uncleaved_dataset, uncleaved_label], axis=1)
uncleaved_dataset_labelled

,ID,A1,C1,D1,E1,F1,G1,H1,I1,K1,...,PCP_AL,PCP_CY,PCP_AR,PCP_AC,PCP_BS,PCP_NE_pH,PCP_HB,PCP_HL,PCP_SC,cleavage Status
0,Seq_1,1,0,0,0,0,0,0,0,0,...,0.250,0.000,0.125,0.125,0.375,0.500,0.375,0.375,0.000,uncleaved
1,Seq_2,0,0,0,0,0,0,0,0,0,...,0.250,0.000,0.000,0.125,0.000,0.875,0.500,0.000,0.125,uncleaved
2,Seq_3,0,0,0,0,0,0,0,0,0,...,0.000,0.000,0.125,0.000,0.000,1.000,0.250,0.250,0.250,uncleaved
3,Seq_4,0,0,0,0,0,0,0,0,0,...,0.375,0.125,0.000,0.000,0.125,0.875,0.500,0.375,0.125,uncleaved
4,Seq_5,0,0,0,0,0,1,0,0,0,...,0.250,0.125,0.125,0.000,0.125,0.875,0.250,0.375,0.125,uncleaved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4842,Seq_4843,0,0,0,0,0,0,0,0,0,...,0.375,0.125,0.250,0.000,0.125,0.875,0.750,0.250,0.000,uncleaved
4843,Seq_4844,0,0,0,0,0,0,0,0,0,...,0.500,0.000,0.125,0.000,0.125,0.875,0.250,0.125,0.000,uncleaved
4844,Seq_4845,0,0,0,0,0,0,0,0,0,...,0.375,0.000,0.125,0.125,0.000,0.875,0.375,0.125,0.000,uncleaved
4845,Seq_4846,0,0,0,0,0,0,0,0,0,...,0.375,0.125,0.250,0.250,0.000,0.750,0.375,0.125,0.000,uncleaved
4846,Seq_4847,0,0,0,0,0,0,0,0,0,...,0.250,0.000,0.250,0.125,0.000,0.875,0.250,0.000,0.000,uncleaved

# Combine the cleaved_dataset_labelled and uncleaved_dataset_labelled

In [19]:
combined_extracted_octapeptide_features = pd.concat([cleaved_dataset_labelled, uncleaved_dataset_labelled], axis=0)
combined_extracted_octapeptide_features

,ID,A1,C1,D1,E1,F1,G1,H1,I1,K1,...,PCP_AL,PCP_CY,PCP_AR,PCP_AC,PCP_BS,PCP_NE_pH,PCP_HB,PCP_HL,PCP_SC,cleavage Status
0,Seq_1,1,0,0,0,0,0,0,0,0,...,0.250,0.000,0.250,0.250,0.125,0.625,0.625,0.125,0.125,cleaved
1,Seq_2,0,0,0,0,0,0,1,0,0,...,0.625,0.000,0.125,0.125,0.125,0.750,0.625,0.125,0.000,cleaved
2,Seq_3,0,0,0,0,0,0,0,0,0,...,0.125,0.000,0.250,0.125,0.000,0.875,0.750,0.000,0.125,cleaved
3,Seq_4,1,0,0,0,0,0,0,0,0,...,0.500,0.000,0.125,0.375,0.000,0.625,0.625,0.000,0.000,cleaved
4,Seq_5,0,0,0,0,0,0,0,0,0,...,0.375,0.250,0.250,0.375,0.000,0.625,0.625,0.250,0.000,cleaved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4842,Seq_4843,0,0,0,0,0,0,0,0,0,...,0.375,0.125,0.250,0.000,0.125,0.875,0.750,0.250,0.000,uncleaved
4843,Seq_4844,0,0,0,0,0,0,0,0,0,...,0.500,0.000,0.125,0.000,0.125,0.875,0.250,0.125,0.000,uncleaved
4844,Seq_4845,0,0,0,0,0,0,0,0,0,...,0.375,0.000,0.125,0.125,0.000,0.875,0.375,0.125,0.000,uncleaved
4845,Seq_4846,0,0,0,0,0,0,0,0,0,...,0.375,0.125,0.250,0.250,0.000,0.750,0.375,0.125,0.000,uncleaved
4846,Seq_4847,0,0,0,0,0,0,0,0,0,...,0.250,0.000,0.250,0.125,0.000,0.875,0.250,0.000,0.000,uncleaved

# Feature Selection of our combined_extracted_octapeptide_features

In [21]:
## VarianceThreshold ised to remove low variance features from the feature variables
from sklearn.feature_selection import VarianceThreshold

In [22]:
## Assigning the feature variables to X
X = combined_extracted_octapeptide_features.drop(["cleavage Status", "ID"], axis=1)
X

,A1,C1,D1,E1,F1,G1,H1,I1,K1,L1,...,PCP_NP,PCP_AL,PCP_CY,PCP_AR,PCP_AC,PCP_BS,PCP_NE_pH,PCP_HB,PCP_HL,PCP_SC
0,1,0,0,0,0,0,0,0,0,0,...,0.500,0.250,0.000,0.250,0.250,0.125,0.625,0.625,0.125,0.125
1,0,0,0,0,0,0,1,0,0,0,...,0.625,0.625,0.000,0.125,0.125,0.125,0.750,0.625,0.125,0.000
2,0,0,0,0,0,0,0,0,0,0,...,0.500,0.125,0.000,0.250,0.125,0.000,0.875,0.750,0.000,0.125
3,1,0,0,0,0,0,0,0,0,0,...,0.625,0.500,0.000,0.125,0.375,0.000,0.625,0.625,0.000,0.000
4,0,0,0,0,0,0,0,0,0,0,...,0.625,0.375,0.250,0.250,0.375,0.000,0.625,0.625,0.250,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4842,0,0,0,0,0,0,0,0,0,0,...,0.500,0.375,0.125,0.250,0.000,0.125,0.875,0.750,0.250,0.000
4843,0,0,0,0,0,0,0,0,0,0,...,0.500,0.500,0.000,0.125,0.000,0.125,0.875,0.250,0.125,0.000
4844,0,0,0,0,0,0,0,0,0,0,...,0.375,0.375,0.000,0.125,0.125,0.000,0.875,0.375,0.125,0.000
4845,0,0,0,0,0,0,0,0,0,0,...,0.500,0.375,0.125,0.250,0.250,0.000,0.750,0.375,0.125,0.000
4846,0,0,0,0,0,0,0,0,0,0,...,0.250,0.250,0.000,0.250,0.125,0.000,0.875,0.250,0.000,0.000

In [23]:
selector = VarianceThreshold()
result = selector.fit_transform(X)
df =pd.DataFrame(result)
df

,0,1,2,3,4,5,6,7,8,9,...,168,169,170,171,172,173,174,175,176,177
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.500,0.250,0.000,0.250,0.250,0.125,0.625,0.625,0.125,0.125
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.625,0.625,0.000,0.125,0.125,0.125,0.750,0.625,0.125,0.000
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.500,0.125,0.000,0.250,0.125,0.000,0.875,0.750,0.000,0.125
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.625,0.500,0.000,0.125,0.375,0.000,0.625,0.625,0.000,0.000
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.625,0.375,0.250,0.250,0.375,0.000,0.625,0.625,0.250,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.500,0.375,0.125,0.250,0.000,0.125,0.875,0.750,0.250,0.000
5844,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.500,0.500,0.000,0.125,0.000,0.125,0.875,0.250,0.125,0.000
5845,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.375,0.375,0.000,0.125,0.125,0.000,0.875,0.375,0.125,0.000
5846,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.500,0.375,0.125,0.250,0.250,0.000,0.750,0.375,0.125,0.000
5847,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.250,0.250,0.000,0.250,0.125,0.000,0.875,0.250,0.000,0.000

**Observe that there was no change in the dimension of the dataset indicating that no two features are the same**

# Drop the ID Column and Save the combined_extracted_octapeptide_features

In [ ]:
df_with_no_id = combined_extracted_octapeptide_features.drop("ID", axis=1)
df_with_no_id.to_csv("final_combined_extracted_features_dataset/final_combined_extracted_octapeptide_features.csv")